// The head and the sidecars are the half of the build a model never touches, so they are checked
// against the one other implementation of the same conventions: templates/personas/tools/emit-seo.mjs,
// which the eight templates' own index.md and llms.txt are generated by. If the two disagree, a
// generated client page and a hand-built template page stop being the same kind of document.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { loadHtml } from '../src/checks/html.js';
import { loadIndustries } from '../src/personas/load.js';
import { buildPageJsonLd, pageLlmsTxt, pageMarkdown, patchHead, readFaq, readSections, type PageSeoContext } from '../src/site/page-seo.js';
import type { Entities } from '../src/site/types.js';
import type { Facts } from '../src/checks/facts.js';
import { REPO_ROOT } from './helpers.js';

const FACTS: Facts = {
  business_name: 'Verdant Grounds',
  phones: ['(503) 555-0142'],
  emails: ['office@verdantgrounds.example'],
  address: { '@type': 'PostalAddress', streetAddress: '77 Alder Street', addressLocality: 'Hillsboro', addressRegion: 'OR', postalCode: '97123' },
  hours: ['Mo-Fr 08:00-16:00'],
  services: ['Patios'],
  sources: {},
};

const sourced = { kind: 'source' as const, page_url: 'https://verdantgrounds.example/', quote: 'q' };
const ENTITIES: Entities = {
  services: [{ name: 'Paver patios', detail: 'Installed by our own crew', source: sourced }],
  areas: [{ name: 'Hillsboro', detail: '', source: sourced }],
  credentials: [],
  price_statements: [],
  rating: { value: '4.8', count: '112', source: sourced },
};

const ctx = (over: Partial<PageSeoContext> = {}): PageSeoContext => ({
  profile: 'production',
  baseUrl: 'https://verdantgrounds.example',
  jsonldType: 'LocalBusiness',
  facts: FACTS,
  businessName: 'Verdant Grounds',
  siteSummary: 'Landscape construction in Hillsboro, Oregon.',
  title: 'Verdant Grounds — patios and drainage in Hillsboro, Oregon',
  metaDescription: 'Verdant Grounds designs and builds paver patios, retaining walls and drainage across Hillsboro and Beaverton, Oregon.',
  entities: ENTITIES,
  assets: [],
  buildDate: '2026-09-18',
  ...over,
});

const PAGE = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hollow Creek Landscape Co.</title>
  <meta name="description" content="The mock business's description, which must not survive.">
  <meta name="theme-color" content="#16251c">
  <link rel="canonical" href="https://hollowcreeklandscape.com/">
  <meta property="og:title" content="Hollow Creek Landscape Co.">
  <script type="application/ld+json" data-checklist="structured-data jsonld-localbusiness">{"@context":"https://schema.org","@graph":[{"@type":"LocalBusiness","name":"Hollow Creek Landscape Co."}]}</script>
</head>
<body><header><nav><a class="skip-link" href="#main">Skip</a></nav></header>
<main id="main">
  <section class="hero" id="hero"><h1>Patios and drainage in Hillsboro</h1><p data-answer-first>Verdant Grounds builds paver patios across Hillsboro.</p></section>
  <section id="services" aria-labelledby="services-h"><h2 id="services-h">What we build</h2>
    <p data-answer-first>Two crews: one installs hardscape, one mows.</p>
    <h3>Paver patios</h3><p>Compacted base, edge restraint, polymeric sand.</p>
    <dl><div><dt>Site visit</dt><dd>Within 7 days</dd></div></dl>
  </section>
  <section id="faq" aria-labelledby="faq-h"><h2 id="faq-h">Frequently asked questions</h2>
    <details><summary><h3 data-faq-q>Do you work in my town?</h3></summary><p data-faq-a>We work across Hillsboro and Beaverton.</p></details>
    <details><summary><h3 data-faq-q>Do you handle design?</h3></summary><p data-faq-a>Yes, every project starts with a measured plan.</p></details>
  </section>
</main>
<footer><nav><a href="#main">Top</a></nav></footer></body></html>`;

test('the FAQ is read back out of the rendered page, in order', () => {
  const faq = readFaq(loadHtml(PAGE));
  assert.deepEqual(faq, [
    { q: 'Do you work in my town?', a: 'We work across Hillsboro and Beaverton.' },
    { q: 'Do you handle design?', a: 'Yes, every project starts with a measured plan.' },
  ]);
});

test('FAQPage mirrors the rendered FAQ verbatim, so checkAeo passes by construction', () => {
  const $ = loadHtml(PAGE);
  const faq = readFaq($);
  const graph = buildPageJsonLd(ctx(), faq)['@graph'] as Record<string, unknown>[];
  const faqNode = graph.find((n) => n['@type'] === 'FAQPage') as { mainEntity: { name: string; acceptedAnswer: { text: string } }[] };
  assert.deepEqual(
    faqNode.mainEntity.map((q) => [q.name, q.acceptedAnswer.text]),
    faq.map((f) => [f.q, f.a]),
  );
});

test('the graph states only what the facts and sourced entities support', () => {
  const graph = buildPageJsonLd(ctx(), [])['@graph'] as Record<string, unknown>[];
  const org = graph.find((n) => n['@type'] === 'LocalBusiness') as Record<string, unknown>;
  assert.equal(org.telephone, '(503) 555-0142');
  assert.equal(org.email, 'office@verdantgrounds.example');
  assert.equal((org.address as Record<string, string>).streetAddress, '77 Alder Street');
  assert.deepEqual(org.areaServed, [{ '@type': 'Place', name: 'Hillsboro' }]);
  assert.equal((org.aggregateRating as Record<string, string>).ratingValue, '4.8');
  assert.ok(graph.some((n) => n['@type'] === 'WebSite'));
  assert.ok(graph.some((n) => n['@type'] === 'WebPage'));
  // No FAQ on the page means no FAQPage node claiming one.
  assert.ok(!graph.some((n) => n['@type'] === 'FAQPage'));
});

test('a rating with no source quote is not emitted, however plausible it looks', () => {
  const unsourced: Entities = { ...ENTITIES, rating: { value: '4.9', count: '300', source: { kind: 'placeholder', page_url: null, quote: null } } };
  const graph = buildPageJsonLd(ctx({ entities: unsourced }), [])['@graph'] as Record<string, unknown>[];
  const org = graph.find((n) => n['@type'] === 'LocalBusiness') as Record<string, unknown>;
  assert.equal(org.aggregateRating, undefined);
});

test("patchHead replaces every part of the head that names the template's business", () => {
  const $ = loadHtml(PAGE);
  const res = patchHead($, ctx());
  const head = $('head').html() ?? '';
  for (const token of ['Hollow Creek Landscape Co.', 'hollowcreeklandscape.com', "The mock business's description"]) {
    assert.ok(!head.includes(token), `the head still says: ${token}`);
  }
  assert.equal($('title').text(), res.title);
  assert.equal($('meta[name="description"]').attr('content'), res.metaDescription);
  assert.equal($('link[rel="canonical"]').attr('href'), 'https://verdantgrounds.example/');
  assert.equal($('meta[property="og:title"]').length, 1, 'exactly one og:title, not the template one plus ours');
  // What the persona chose and the client has no opinion on is left alone.
  assert.equal($('meta[name="theme-color"]').attr('content'), '#16251c');
  // The JSON-LD block keeps the audit tags the template put on it.
  assert.equal($('script[type="application/ld+json"]').attr('data-checklist'), 'structured-data jsonld-localbusiness');
  assert.equal($('script[type="application/ld+json"]').length, 1);
  assert.match($('script[type="application/ld+json"]').text(), /Verdant Grounds/);
});

test('title and description are clamped into the audit\'s own windows', () => {
  const $ = loadHtml(PAGE);
  const res = patchHead($, ctx({ title: 'x'.repeat(200), metaDescription: 'y '.repeat(200) }));
  assert.ok(res.title.length <= 70, `title ${res.title.length}`);
  assert.ok(res.metaDescription.length <= 170, `description ${res.metaDescription.length}`);
});

test('a mockup profile ships no canonical, because a preview is not published anywhere', () => {
  const $ = loadHtml(PAGE);
  patchHead($, ctx({ profile: 'mockup' }));
  assert.equal($('link[rel="canonical"]').length, 0);
  assert.equal($('meta[property="og:url"]').length, 0);
  assert.equal($('link[rel="alternate"][type="text/markdown"]').length, 0);
  // The structured data is still rebuilt: it is what the self-test checks.
  assert.match($('script[type="application/ld+json"]').text(), /Verdant Grounds/);
});

test('the sidecars are derived from the rendered page', () => {
  const $ = loadHtml(PAGE);
  const res = patchHead($, ctx());
  const md = pageMarkdown($, ctx(), res.faq);
  assert.match(md, /^# Patios and drainage in Hillsboro/);
  assert.match(md, /Verdant Grounds builds paver patios across Hillsboro\./);
  assert.match(md, /## What we build/);
  assert.match(md, /\*\*Paver patios:\*\* Compacted base/);
  assert.match(md, /- \*\*Site visit:\*\* Within 7 days/);
  assert.match(md, /### Do you work in my town\?/);
  // The FAQ section is rendered once, from the structured list, not twice.
  assert.equal(md.match(/## Frequently asked questions/g)?.length, 1);

  const llms = pageLlmsTxt($, ctx(), res.faq);
  assert.match(llms, /^# Verdant Grounds/);
  assert.match(llms, /- Phone: \(503\) 555-0142/);
  assert.match(llms, /- Email: office@verdantgrounds\.example/);
  assert.match(llms, /- Address: 77 Alder Street, Hillsboro, OR, 97123/);
  assert.match(llms, /- Areas served: Hillsboro/);
  assert.match(llms, /- Services: Paver patios/);
  assert.match(llms, /- Rating: 4\.8 from 112 reviews/);
  assert.match(llms, /## Questions this site answers/);
  assert.match(llms, /- Do you handle design\?/);
});

test('readSections agrees with tools/emit-seo.mjs on a real template page', async () => {
  // The anti-drift guarantee. emit-seo.mjs generates the eight templates' own index.md; this code
  // generates a client build's. They must walk a page the same way.
  const industries = loadIndustries(REPO_ROOT);
  const industry = industries.industries.find((i) => i.slug === 'landscaping')!;
  const html = fs.readFileSync(path.join(REPO_ROOT, industry.template_file), 'utf8');
  const $ = loadHtml(html);

  const mine = readSections($);
  const theirs = (await import(path.join(REPO_ROOT, 'templates/personas/tools/emit-seo.mjs'))) as {
    sectionsOf?: (api: unknown) => { h2: string; blocks: string[] }[];
  };
  if (!theirs.sectionsOf) {
    // Not exported yet — assert the shape instead of silently passing.
    assert.ok(mine.length >= 5, `expected >= 5 sections, got ${mine.length}`);
    assert.ok(mine.every((s) => s.h2.length > 0));
    assert.ok(mine.some((s) => /frequently asked questions/i.test(s.h2)), 'the FAQ section is found');
    return;
  }
  assert.deepEqual(mine, theirs.sectionsOf($));
});
